/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface OTPGeneratorInterface extends Interface {
  getFunction(
    nameOrSignature: "generateOTP" | "otps" | "verifyOTP"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "generateOTP",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "otps", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "verifyOTP",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "generateOTP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "otps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifyOTP", data: BytesLike): Result;
}

export interface OTPGenerator extends BaseContract {
  connect(runner?: ContractRunner | null): OTPGenerator;
  waitForDeployment(): Promise<this>;

  interface: OTPGeneratorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  generateOTP: TypedContractMethod<[], [bigint], "nonpayable">;

  otps: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  verifyOTP: TypedContractMethod<[otp: BigNumberish], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "generateOTP"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "otps"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyOTP"
  ): TypedContractMethod<[otp: BigNumberish], [boolean], "view">;

  filters: {};
}
